---
- name: playbook to provision most of the MoodleBox
  hosts: all
  become: yes

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: include customised variables
      include_vars: "{{ item }}"
      with_fileglob:
        - config.yml

  roles:
    - bootstrap
    - install
    - network
    - moodle
    - cleanup

  vars:
    ansible_user: 'root'
