---

- name: get MathJax library from git repository
  git:
    repo: 'git://github.com/mathjax/MathJax.git'
    dest: '{{ moodlebox_moodle_source_dir }}/lib/MathJax'
    version: '{{ moodlebox_mathjax_version }}'
    depth: 1

- name: change MathJax library file permissions
  file:
    path: '{{ moodlebox_moodle_source_dir }}/lib/MathJax'
    state: 'directory'
    owner: '{{ moodlebox_username }}'
    group: 'www-data'
    mode: 'ug+w,o-w'
    recurse: 'yes'
