---

- name: add apt-key for PHP7.2 apt repository
  apt_key:
    url: 'https://packages.sury.org/php/apt.gpg'
    state: 'present'

- name: add PHP7.2 apt repository
  apt_repository:
    repo: 'deb https://packages.sury.org/php/ stretch main'
    filename: 'php.list'
    state: 'present'

- name: uninstall useless packages
  apt:
    pkg: '{{ item }}'
    state: 'absent'
    purge: 'yes'
  with_flattened:
    - '{{ moodlebox_uninstall_packages }}'
  when: 'moodlebox_uninstall_packages is defined'

- name: install packages
  apt:
    pkg: '{{ item }}'
    state: 'present'
  with_flattened:
    - '{{ moodlebox_install_packages }}'

- name: install phpMyAdmin package
  apt:
    pkg: 'phpmyadmin'
    state: 'present'

- name: install custom phpMyAdmin configuration file
  copy:
    src: 'etc/phpmyadmin/conf.d/moodlebox.inc.php'
    dest: '/etc/phpmyadmin/conf.d/moodlebox.inc.php'
    mode: 0644

- name: copy usbmount deb package file
  copy:
    src: 'usbmount_0.0.24_all.deb'
    dest: '/tmp/usbmount_0.0.24_all.deb'

- name: install usbmount package
  apt:
    deb: '/tmp/usbmount_0.0.24_all.deb'

- name: delete usbmount deb package file
  file:
    path: '/tmp/usbmount_0.0.24_all.deb'
    state: 'absent'
